version: "3.6"
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: "postgres:12"
    restart: always
    ports:
      - 6543:5432
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata:
